/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectfour;

import javax.swing.JOptionPane; // Used to error handle

/**
 * Gui for the intro screen of the game
 * @author Colin Chambachan
 * date: August 24th, 2020
 */
public class IntroScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form IntroScreen
     */
    public IntroScreen() {
        initComponents();
        // Make the Gui visible
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTodaysDate = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        lblDay = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        lblMonth = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        btnPlayGame = new javax.swing.JButton();
        lblSubtitle = new javax.swing.JLabel();
        lblDescription1 = new javax.swing.JLabel();
        lblDescription2 = new javax.swing.JLabel();
        lblDescription3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitle.setText("Welcome to Connect Four!");

        lblTodaysDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTodaysDate.setText("Enter Todays Date (Tracks Your Win Total for Today):");

        lblDay.setText("Enter the day (DD):");

        lblMonth.setText("Enter the Month (MM):");

        lblYear.setText("Enter the Year (YYYY):");

        btnPlayGame.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPlayGame.setText("Let Me Play!");
        btnPlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayGameActionPerformed(evt);
            }
        });

        lblSubtitle.setText("(Made With Java On NetBeans 8.2)");

        lblDescription1.setText("Welcome to Connect 4! In this game, two players will take turns dropping disks");

        lblDescription2.setText("into a 7x6 grid. Win the game by connecting four disks horizontally, veritcally, or");

        lblDescription3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescription3.setText("diagonally before your opponent does! Good luck and have fun!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblYear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTodaysDate)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDay)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonth)
                            .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnPlayGame)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription1)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblSubtitle))
                    .addComponent(lblDescription2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblDescription3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(22, 22, 22)
                .addComponent(lblDescription1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescription2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescription3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(lblTodaysDate)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDay)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblMonth)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(btnPlayGame)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Collect the user given data and open up the main screen GUI
     * @param evt is when the event occurs
     */
    private void btnPlayGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayGameActionPerformed
        // Make sure that all the fields are not empty
        if (!txtDay.getText().equals("") && !txtMonth.getText().equals("") && !txtYear.getText().equals("") ){
            // Get Todays Date
            String strTodaysDate = txtDay.getText() + "/" + txtMonth.getText() + "/" + txtYear.getText();
        
            // Call the MainScreen Gui and set own gui to be false, pass the date that the user entered in as well
            MainScreen main = new MainScreen(strTodaysDate);
            setVisible(false);
        } else{
            // Send a pop up to tell the user to 
            JOptionPane.showMessageDialog(null, "Please enter a valid date before proceeding!");
        }    
            
    }//GEN-LAST:event_btnPlayGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlayGame;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblDescription2;
    private javax.swing.JLabel lblDescription3;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTodaysDate;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
